version: '3'

services:
  karasu:
    restart: always
    # if you want to build from scratch (not recommended)
    # build: .
    image: "krasjet/karasu"
    # copy .env.example to .env
    env_file:
     - ./.env
    expose:
      - "${KARASU_PORT}"
    volumes:
      - ./run/db:/app/db/
      - ./run/view:/app/view/
      - ./run/cache:/app/cache/
      - ./run/backup:/app/backup/
      - static:/app/static
  kamome:
    restart: always
    build: ./kamome/
    image: "kamome"
    env_file:
     - ./.env
    environment:
     - NGINX_HOST=localhost
     # keys for SSL
     - SSL_CERT=cert.pem
     - SSL_KEY=cert.key
    volumes:
     - ./kamome/nginx/http.template:/etc/nginx/nginx.template
     # If you want to use SSL
     # - ./kamome/nginx/https.template:/etc/nginx/nginx.template
     - ./run/view/:/app/view/
     - ./certs:/etc/ssl/certs
     - static:/app/
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$KARASU_PORT' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - karasu

volumes:
  static:
